# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import asciiart_pb2 as asciiart__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in asciiart_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AsciiArtServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateArt = channel.unary_unary(
                '/asciiart.AsciiArtService/GenerateArt',
                request_serializer=asciiart__pb2.ArtRequest.SerializeToString,
                response_deserializer=asciiart__pb2.ArtResponse.FromString,
                _registered_method=True)
        self.GetArtStyles = channel.unary_unary(
                '/asciiart.AsciiArtService/GetArtStyles',
                request_serializer=asciiart__pb2.StyleRequest.SerializeToString,
                response_deserializer=asciiart__pb2.StyleResponse.FromString,
                _registered_method=True)


class AsciiArtServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateArt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArtStyles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AsciiArtServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateArt': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateArt,
                    request_deserializer=asciiart__pb2.ArtRequest.FromString,
                    response_serializer=asciiart__pb2.ArtResponse.SerializeToString,
            ),
            'GetArtStyles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArtStyles,
                    request_deserializer=asciiart__pb2.StyleRequest.FromString,
                    response_serializer=asciiart__pb2.StyleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'asciiart.AsciiArtService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('asciiart.AsciiArtService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AsciiArtService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateArt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asciiart.AsciiArtService/GenerateArt',
            asciiart__pb2.ArtRequest.SerializeToString,
            asciiart__pb2.ArtResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArtStyles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asciiart.AsciiArtService/GetArtStyles',
            asciiart__pb2.StyleRequest.SerializeToString,
            asciiart__pb2.StyleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
