# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: asciiart.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'asciiart.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61sciiart.proto\x12\x08\x61sciiart\")\n\nArtRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05style\x18\x02 \x01(\t\"\x1a\n\x0b\x41rtResponse\x12\x0b\n\x03\x61rt\x18\x01 \x01(\t\"\x0e\n\x0cStyleRequest\"\x1f\n\rStyleResponse\x12\x0e\n\x06styles\x18\x01 \x03(\t2\x92\x01\n\x0f\x41sciiArtService\x12<\n\x0bGenerateArt\x12\x14.asciiart.ArtRequest\x1a\x15.asciiart.ArtResponse\"\x00\x12\x41\n\x0cGetArtStyles\x12\x16.asciiart.StyleRequest\x1a\x17.asciiart.StyleResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asciiart_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARTREQUEST']._serialized_start=28
  _globals['_ARTREQUEST']._serialized_end=69
  _globals['_ARTRESPONSE']._serialized_start=71
  _globals['_ARTRESPONSE']._serialized_end=97
  _globals['_STYLEREQUEST']._serialized_start=99
  _globals['_STYLEREQUEST']._serialized_end=113
  _globals['_STYLERESPONSE']._serialized_start=115
  _globals['_STYLERESPONSE']._serialized_end=146
  _globals['_ASCIIARTSERVICE']._serialized_start=149
  _globals['_ASCIIARTSERVICE']._serialized_end=295
# @@protoc_insertion_point(module_scope)
